name: CI First Run #Tên pipeline (hiển thị trên GitHub)

on: push #Trigger – khi nào chạy

jobs: #Danh sách job
  hello:
    runs-on: ubuntu-latest #Máy ảo chạy job
    steps: #Các bước thực thi
      - name: Say hello
        run: echo "CI/CD is running successfully" #Chạy lệnh shell
